# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hg0ZjA_UZIwssZJA3uNrqCJiHN4aYhzH
"""

knap=[]
profit=0
print(" Knapsack problem ")
n=int(input(" Enter how many objects are there "))
M=float(input(" Enter the fixed/maximum weight "))
p=[]
w=[]
for i in range(0,n):
  a=[]
  for j in range(0,3):
    if(j==0):
      print(" Enter Weight of no. ",i+1," object: ")
      a.append(int(input()))
    elif(j==1):
      print(" Enter Profit of no. ",i+1," object: ")
      a.append(int(input()))
    else:
      r=a[1]/a[0]
      print(" Profit/Weight ratio of ",i+1," object= ",r)
      a.append(r)
  knap.append(a)
#print(knap)
for i in range(0,n):
  max=i
  for j in range(i+1,3):
    if(knap[j][2]>knap[max][2]):
      max=j
  for k in range(0,3):
    c=knap[i][k]+knap[max][k]
    knap[i][k]=c-knap[i][k]
    knap[max][k]=c-knap[i][k]
#print(knap)
print("\n \n We want to maximize the profit")
for i in range(0,n):
  w.append(knap[i][0])
  p.append(knap[i][1])
#print(w)
#print(p)
for i in range(0,n):
  if(M>0 and w[i]<M):
    M=M-w[i]
    profit=profit+p[i]
  else:
    break;
  if(M>0):
    profit=profit+p[i+1]*(M/w[i+1])
print(" Maximum profit is ",profit)